/*******************************************************************************************************
* Class Name      	: QuoteLineGroupModel
* Description		: CPQ Model Class for Quote Line Group
* Author          	: Simplus - Gerald Arzadon	
* Created On      	: 1-13-2020
* -----------------------------------------------------------------------------------------------------
* Developer				Date				Description
* -----------------------------------------------------------------------------------------------------
* Gerald Arzadon    	1-13-2020			Initial version 
******************************************************************************************************/
public class QuoteLineGroupModel {
    public SBQQ__QuoteLineGroup__c record;
    public Decimal netNonSegmentTotal;
    public Integer key;
}